### ISSUE TITLE
Adding gray characters in every square

### ISSUE THREAD

**Issue by rleyvasal** [lucivpav/cwg#53]
Is it possible to add the option to have gray characters on every square of the worksheet?. Having gray characters to trace helps young kids memorize - the first character is already gray.

**Comment by lucivpav** [comment]
Hello, thanks for the suggestion. I am busy recently, but I will look at your proposal reply you, eventually. Please be patient.

**Comment by rleyvasal** [comment]
> 
> 
> Hello, thanks for the suggestion. I am busy recently, but I will look at your proposal and reply you, eventually. Please be patient.

**Comment by rleyvasal** [comment]
Thanks for the quick reply. I understand you may be busy, take your time

**Comment by rleyvasal** [comment]
Thanks for the quick response. I think I deleted my comment, in any case
take your time, I know life is complicated for everyone right now.

Rigoberto

**Comment by lucivpav** [comment]
And another user has requested this feature.

**Comment by lucivpav** [comment]
@rleyvasal the feature has been implemented, feedback is welcome. Enjoy :)

PS: you may need to force refresh the website for the new change to work.

![image](https://user-images.githubusercontent.com/10930160/167315116-ed3a6968-75c0-4755-946b-ba0e605e5da8.png)
