### ISSUE TITLE
Adding gray characters to every square in the worksheet

### ISSUE THREAD

**Issue by rleyvasal** [lucivpav/cwg#54]
Gray characters on squares would be great for young kids to trace  - take your time working on this. 

P.S. I deleted my previous request by mistake.

**Comment by lucivpav** [comment]
Hi Rigoberto, You have pressed the `Close issue` button. When the issue is closed, it can be still found among the Closed issues. Anyways, I have re-opened the original issue. I am closing this new issue now.

**Comment by rleyvasal** [comment]
Thanks
